package com.crime.management.model.Enums;

public enum PoliceStationName {
    CENTRAL_POLICE_STATION,
    NORTH_DIVISION,
    SOUTH_DIVISION,
    EAST_SIDE_POLICE_STATION,
    WEST_SIDE_POLICE_STATION,
    CITY_CENTER_POLICE_STATION,
    RIVERSIDE_POLICE_STATION,
    HILL_VIEW_POLICE_STATION,
    DOWNTOWN_POLICE_STATION,
    OLD_TOWN_POLICE_STATION
}
